FROM composer

RUN apk update \
 && apk add libzip-dev \
 && apk add libpng-dev \
 && docker-php-ext-install zip \
 && docker-php-ext-install gd
RUN composer create-project getgrav/grav ~/webroot/grav
WORKDIR /var/www/html
RUN addgroup -g 1000 app \
 && adduser  -u 1000 -G app -S app
USER app
CMD [ "php", "-S",  "0.0.0.0:8000",  "system/router.php" ]
